---
title: "Disseny d'experiments"
author: "Marc Comas i Marina Vives"
date: "16 de desembre"
output: 
  ioslides_presentation: 
    smaller: yes
---

```{r, echo=FALSE}
data(birthwt, package='MASS')
```

# Dissenys factorials

## Creació disseny factorial

  * Necessitarem el plugin per Rcommander `RcmdrPlugin.DoE`
  
```{r, message=FALSE,warning=FALSE}
# install.packages("RcmdrPlugin.DoE")
library(RcmdrPlugin.DoE)
```

  * Disseny 2^k (k=3)
  
```{r, include=FALSE}
vr = c(10.03,10.30,10.70,11.37,8.68,9.08,9.60,9.91)
```

```{r, include=FALSE, message=FALSE}
Design.1 <- fac.design(nfactors= 3 ,replications= 1 ,repeat.only= FALSE ,
  blocks= 1 ,randomize= FALSE ,seed= 30559 ,nlevels=c( 2,2,2 ), 
  factor.names=list( A=c(-1,1),B=c(-1,1),C=c(-1,1) ) )
Design.1 <- add.response(Design.1,vr, replace=FALSE)
LinearModel.1 <- lm(vr ~ (A + B + C), data=Design.1)
```

Resposta

```{r, eval=FALSE}
vr = c(10.03,10.30,10.70,11.37,8.68,9.08,9.60,9.91)
```

## Gràfics bàsics de diagnòstic

Els residus han de ser independents, homocedàstics i normals

```{r, fig.width=7.5, fig.height=5, echo=FALSE}
par(mfrow=c(2,2))
plot(LinearModel.1)
par(mfrow=c(1,1))
```

## Central composite designs

Response surface analysis
